@testset "HOPE Smoke" begin
    @test isdefined(HOPE, :run_hope)
    @test isdefined(HOPE, :create_PCM_model)
    @test isdefined(HOPE, :marginal_load_price_from_dual)
    @test !isdefined(HOPE, :configure_settings)

    @test isdefined(HOPE, :get_representative_ts)
    @test isdefined(HOPE, :get_TPmatched_ts)
    @test isdefined(HOPE, :get_project_root)
    @test isdefined(HOPE, :get_case_paths)
    @test isdefined(HOPE, :get_paths)
    @test isdefined(HOPE, :validate_case_directory)
    @test isdefined(HOPE, :validate_model_mode)
    @test isdefined(HOPE, :safe_file_read)
    @test isdefined(HOPE, :safe_remove_directory)
    @test isdefined(HOPE, :ensure_output_directory)
    @test isdefined(HOPE, :apply_technology_mapping)
    @test isdefined(HOPE, :aggregate_capacity_data)
    @test isdefined(HOPE, :debug)
    @test isdefined(HOPE, :run_debug)
    @test isdefined(HOPE, :COLOR_MAP)
    @test isdefined(HOPE, :TECH_ACRONYM_MAP)
    @test isdefined(HOPE, :ORDERED_TECH_POWER)
    @test isdefined(HOPE, :ORDERED_TECH_CAPACITY)
    @test isdefined(HOPE, :ORDERED_ES_TECH)
    @test isdefined(HOPE, :VALID_MODEL_MODES)
    @test isdefined(HOPE, :HOURS_PER_YEAR)
    @test isdefined(HOPE, :REQUIRED_FILES)

    @test !Base.isexported(HOPE, :get_representative_ts)
    @test !Base.isexported(HOPE, :get_TPmatched_ts)
    @test !Base.isexported(HOPE, :get_project_root)
    @test !Base.isexported(HOPE, :get_case_paths)
    @test !Base.isexported(HOPE, :get_paths)
    @test !Base.isexported(HOPE, :validate_case_directory)
    @test !Base.isexported(HOPE, :validate_model_mode)
    @test !Base.isexported(HOPE, :safe_file_read)
    @test !Base.isexported(HOPE, :safe_remove_directory)
    @test !Base.isexported(HOPE, :ensure_output_directory)
    @test !Base.isexported(HOPE, :apply_technology_mapping)
    @test !Base.isexported(HOPE, :aggregate_capacity_data)
    @test !Base.isexported(HOPE, :debug)
    @test !Base.isexported(HOPE, :run_debug)
    @test !Base.isexported(HOPE, :COLOR_MAP)
    @test !Base.isexported(HOPE, :TECH_ACRONYM_MAP)
    @test !Base.isexported(HOPE, :ORDERED_TECH_POWER)
    @test !Base.isexported(HOPE, :ORDERED_TECH_CAPACITY)
    @test !Base.isexported(HOPE, :ORDERED_ES_TECH)
    @test !Base.isexported(HOPE, :VALID_MODEL_MODES)
    @test !Base.isexported(HOPE, :HOURS_PER_YEAR)
    @test !Base.isexported(HOPE, :REQUIRED_FILES)

    case_dir, output_dir = HOPE.get_case_paths("MD_GTEP_clean_case")
    output_dir2, case_dir2 = HOPE.get_paths("MD_GTEP_clean_case")
    @test case_dir == case_dir2
    @test output_dir == output_dir2
    @test endswith(output_dir, joinpath("ModelCases", "MD_GTEP_clean_case", "output"))
end
