name: "Usage question"
description: Questions related to the usage
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!

        Please, before submitting, make sure that:

        - You have checked the [documentation](https://hope-model-project.github.io/HOPE/) and haven't found enough information
        - There is not an [existing issue](https://github.com/HOPE-Model-Project/HOPE/issues) with the same question
        - You have read the [contributing guide](https://hope-model-project.github.io/HOPE/dev/90-contributing/)
        - You are following the [code of conduct](https://github.com/HOPE-Model-Project/HOPE/blob/master-dev/CODE_OF_CONDUCT.md)
        The form below should help you in filling out this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write your question
    validations:
      required: true
