clean_energy_policy: 0
transmission_loss: 0
time_periods:
  4: "(12, 21, 3, 19)"
  2: "(6, 21, 9, 21)"
  3: "(9, 22, 12, 20)"
  1: "(3, 20, 6, 20)"
inv_dcs_bin: 0
unit_commitment: 2
carbon_policy: 0
model_mode: "PCM"
solver: "clp"
write_shadow_prices: 0
reference_bus: 1
debug: 0
DataCase: "Data_RTS24_PCM_full/"
network_model: 3
summary_table: 1
resource_aggregation: 0
representative_day!: 0
operation_reserve_mode: 2
flexible_demand: 1
