# HOPE Preprocessing Settings for MD_PCM_Excel_DR_case
# This configuration uses full resolution for PCM modeling

# =============================================================================
# TIME CLUSTERING SETTINGS
# =============================================================================

# Disable clustering for PCM (use full 8760 hour resolution)
enable_time_clustering: false
clustering_method: "none"

# =============================================================================
# GENERATOR AGGREGATION SETTINGS  
# =============================================================================

enable_generator_aggregation: true
aggregation_level: "zone_type"

preserve_flags:
  - "Flag_thermal"
  - "Flag_VRE"
  - "Flag_mustrun"
  - "Flag_UC"  # Include unit commitment flag for PCM

# PCM-specific aggregation (include UC parameters)
aggregation_method:
  capacity_params:
    method: "sum"
    parameters:
      - "Pmax (MW)"
      - "Pmin (MW)"
  
  cost_params:
    method: "weighted_mean"
    weight_by: "Pmax (MW)"
    parameters:
      - "Cost ($/MWh)"
      - "Start_up_cost ($/MW)"
  
  technical_params:
    method: "mean"
    parameters:
      - "EF"
      - "CC"
      - "AF"
      - "FOR"
      - "RM_SPIN"
      - "RU"
      - "RD"
  
  time_params:
    method: "max"
    parameters:
      - "Min_down_time"
      - "Min_up_time"

# =============================================================================
# DATA VALIDATION SETTINGS
# =============================================================================

enable_validation: true

validation_rules:
  required_tables:
    - "Zonedata"
    - "Gendata"
    - "Loaddata"
    
  time_series_checks:
    expected_hours: 8760
    allow_partial_year: false

# =============================================================================
# OUTPUT SETTINGS
# =============================================================================

save_intermediate_results: true
output_directory: "preprocessing_output"

save_options:
  aggregated_data: true
  validation_report: true

# =============================================================================
# MODEL COMPATIBILITY SETTINGS
# =============================================================================

target_model_mode: "PCM"

model_options:
  PCM:
    force_full_resolution: true
    include_unit_commitment: true

# =============================================================================
# DEBUGGING SETTINGS
# =============================================================================

debug:
  verbose_output: true
  validate_each_step: true
