DataCase: Data_100RPS/            #String the folder name of data, default Data/ GTEP example: "Data_100RPS/"; PCM eample: "Data_PCM2035/"
model_mode: GTEP                  #"GTEP" or "PCM" or ...
aggregated!: 1                    #1 aggregate technology resource; 0 Does Not
representative_day!: 1            #1 use representative days and set time_periods please; 0 Does Not
inv_dcs_bin: 0                    #1 use integer variable for investment decisions; 0 Does Not
time_periods:                     #representative day clustering, could define yourself
    1 : (3, 20, 6, 20)            # March 20th to June 20th;  1;srping
    2 : (6, 21, 9, 21)            # June 21st to September 21st;  2;summer
    3 : (9, 22, 12, 20)           # September 22nd to December 20th;  3;fall
    4 : (12, 21, 3, 19)           # December 21st to March 19th;  4;winter
planning_reserve_margin: 0.02     #planning_reserve_margin
solver: cbc                    #solver: cbc, groubi

