# Gurobi Solver Parameters
# Common solver settings
Feasib_Tol: 1.0e-05
Optimal_Tol: 1.0e-05
Pre_Solve: 1
Method: 1

# Gurobi-specific solver settings
MIPGap: 1.0e-03
BarConvTol: 1.0e-08
NumericFocus: 3
Crossover: 0
BarObjRng: 1.0e+75
PreDual: 0
AggFill: 10
OutputFlag: 1
